//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<System.TimeSpan> TimeConsume { get; set; }
        public Nullable<System.TimeSpan> TimePenalty { get; set; }
        public int CompetitorId { get; set; }
        public Nullable<System.DateTime> JudgeTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public int JudgeId { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual Event Event { get; set; }
        public virtual Judge Judge { get; set; }
    }
}
